import json
import pathlib

# Paths
ROOT = pathlib.Path(__file__).resolve().parent.parent
DB_PATH = ROOT / "products-data.json"

data = json.loads(DB_PATH.read_text(encoding="utf-8"))
existing_names = {d.get("name") for d in data if isinstance(d, dict)}

new_items_200 = [
    # 男性保養 (Men's Care)
    {"name": "Biore 蜜妮 男士沁涼洗面乳", "features": "薄荷成分、深層去油。", "pain": "油光、汗水、悶熱感。", "skin": "油性肌、男士。", "category": "男性保養"},
    {"name": "L'Oreal 巴黎萊雅 男士勁能保濕能量水", "features": "維他命C、醒膚效果。", "pain": "臉部暗沈、疲勞感、刮鬍後乾燥。", "skin": "男士。", "category": "男性保養"},
    {"name": "Gatsby 潔面濕紙巾 (極凍型)", "features": "超強涼感、立即去油。", "pain": "戶外流汗、無洗臉空間、臉部油膩。", "skin": "所有膚質。", "category": "男性保養"},
    {"name": "UNO 完效男人保濕凍", "features": "五效合一、清爽控油。", "pain": "保養程序太繁瑣、出油。", "skin": "混合肌、油性肌。", "category": "男性保養"},
    {"name": "Mentholatum 曼秀雷敦 男士去油抗痘洗面乳", "features": "含水楊酸、深層清潔。", "pain": "青春痘、黑頭、油光。", "skin": "油痘肌。", "category": "男性保養"},
    {"name": "Lab Series 雅男士 多功能潔面乳", "features": "磨砂顆粒、深層淨化。", "pain": "角質粗厚、毛孔髒污。", "skin": "所有膚質。", "category": "男性保養"},
    {"name": "Kiehl's 契爾氏 男士全效潔面膏", "features": "咖啡因萃取、薄荷舒緩。", "pain": "晨起臉部浮腫、洗後緊繃。", "skin": "所有膚質。", "category": "男性保養"},
    {"name": "Shiseido 資生堂 男士均衡保濕乳", "features": "長效鎖水、質感輕盈。", "pain": "兩頰乾燥、T字出油。", "skin": "混合肌。", "category": "男性保養"},
    {"name": "Biotherm 碧兒泉 男士活泉保濕凝膠", "features": "礦物成分、補水清爽。", "pain": "缺水引起的細紋、油膩感。", "skin": "所有膚質。", "category": "男性保養"},
    {"name": "Gillette 吉列 鋒隱無感刮鬍泡", "features": "潤滑保護、減少紅腫。", "pain": "刮鬍受傷、皮膚發紅、乾燥。", "skin": "所有膚質。", "category": "男性保養"},

    # 保健食品 (Supplements)
    {"name": "DHC 維他命C (60日份)", "features": "高濃度維他命C、日常補充。", "pain": "免疫力、膚色暗沈、作息不正常。", "skin": "所有人。", "category": "保健食品"},
    {"name": "Chocola BB Plus 糖衣錠", "features": "高單位B群、解決口角炎。", "pain": "疲倦、口角炎、皮膚粗糙。", "skin": "成人。", "category": "保健食品"},
    {"name": "Fancl 芳珂 綜合維他命 (30日份)", "features": "完整營養、易吸收。", "pain": "外食族、營養不均、體力不支。", "skin": "成人。", "category": "保健食品"},
    {"name": "Haba 鯊烯美肌膠囊", "features": "高純度鯊烯、由內保濕。", "pain": "皮膚極乾、循環不佳。", "skin": "乾性體質。", "category": "保健食品"},
    {"name": "白蘭氏 萃雞精 (膠原蛋白菁萃)", "features": "高純度精華、滋補養顏。", "pain": "氣色差、產後術後補養、體力差。", "skin": "所有人。", "category": "保健食品"},
    {"name": "三得利 Suntory 芝麻明EX", "features": "助眠成分、提升活力。", "pain": "睡眠品質差、易累、老化。", "skin": "成人。", "category": "保健食品"},
    {"name": "Weider 威德 益生菌", "features": "多種菌種、調整體質。", "pain": "腸胃不適、過敏體質、排便不順。", "skin": "所有人。", "category": "保健食品"},
    {"name": "BHK's 奢華燕窩膠原蛋白", "features": "小分子膠原、燕窩添加。", "pain": "皮膚鬆弛、無光澤、想要醫美感。", "skin": "女性。", "category": "保健食品"},
    {"name": "老協珍 熬雞精", "features": "傳承古法、豐富營養。", "pain": "體質虛弱、成長發育、備孕。", "skin": "所有人。", "category": "保健食品"},
    {"name": "大正製藥 百保能 (維他命補充版)", "features": "舒緩感冒、補充體力。", "pain": "感冒前兆、流鼻水、發熱。", "skin": "成人。", "category": "保健食品"},

    # 香氛 (Fragrance)
    {"name": "Jo Malone 英國梨與小蒼蘭古龍水", "features": "經典香氣、清爽花果調。", "pain": "想要優雅氣息、約會必備。", "skin": "所有人。", "category": "香氛"},
    {"name": "Dior 迪奧 花漾迪奧淡香水", "features": "玫瑰牡丹香、少女感。", "pain": "提升個人魅力、追求名媛感。", "skin": "所有人。", "category": "香氛"},
    {"name": "Chloe 同名女性淡香精", "features": "蜂蜜玫瑰香、經典雋永。", "pain": "職場專業感、自信提升。", "skin": "所有人。", "category": "香氛"},
    {"name": "Diptyque 影中之水淡香水", "features": "黑醋栗葉香、獨特草本。", "pain": "不喜歡大眾香、追求獨特性。", "skin": "所有人。", "category": "香氛"},
    {"name": "Aesop 悟香水", "features": "柚子草本香、療癒感。", "pain": "壓力大、想要放鬆、森林感。", "skin": "所有人。", "category": "香氛"},
    {"name": "Elizabeth Arden 伊麗莎白雅頓 綠茶淡香水", "features": "平價經典、清爽宜人。", "pain": "夏天悶熱、追求清新感、預算有限。", "skin": "所有人。", "category": "香氛"},
    {"name": "The Body Shop 白麝香絲柔淡雅香水", "features": "溫潤麝香、純素成分。", "pain": "追求親和力、舒服皂香。", "skin": "所有人。", "category": "香氛"},
    {"name": "Gucci Bloom 花悅女性淡香水", "features": "白花調、復古包裝。", "pain": "喜歡濃郁花香、追求質感。", "skin": "所有人。", "category": "香氛"},
    {"name": "BYREDO 無人之境淡香精", "features": "乾淨玫瑰香、現代感。", "pain": "追求高級感、中性香愛好者。", "skin": "所有人。", "category": "香氛"},
    {"name": "CK One 中性淡香水", "features": "簡約清新、入門首選。", "pain": "情侶共用、不分場合、簡單日常。", "skin": "所有人。", "category": "香氛"},

    # 更多彩妝 (Makeup)
    {"name": "Excel 裸色深邃眼影 (SR03)", "features": "大地色系、細緻珠光。", "pain": "腫泡眼、化妝新手、職場日常妝。", "skin": "所有膚質。", "category": "彩妝"},
    {"name": "1028 飛激吻唇膏", "features": "柔霧質地、不乾不顯紋。", "pain": "唇紋明顯、霧面唇膏太乾。", "skin": "所有膚質。", "category": "彩妝"},
    {"name": "Maybelline 媚比琳 遮遮稱奇遮瑕膏", "features": "質地水潤、高遮瑕。", "pain": "黑眼圈、痘疤、眼下細紋不卡粉。", "skin": "所有膚質。", "category": "彩妝"},
    {"name": "heme 喜蜜 晶緻亮采餅", "features": "高光提亮、粉質細膩。", "pain": "臉部扁平、無光澤感、五官不立體。", "skin": "所有膚質。", "category": "彩妝"},
    {"name": "Kate 凱婷 進化版持久液體眼線筆 EX 3.0", "features": "極細筆頭、不暈染。", "pain": "眼線畫太粗、手抖、出油暈妝。", "skin": "所有膚質。", "category": "彩妝"},
    {"name": "Clio 珂莉奧 璀璨星沙十色眼影盤", "features": "多種質地、韓系亮片。", "pain": "追求多變妝容、喜歡亮片感。", "skin": "所有膚質。", "category": "彩妝"},
    {"name": "Za 美白粉餅 (升級版)", "features": "乾濕兩用、提亮膚色。", "pain": "補妝不便、暗沈、平價首選。", "skin": "混合肌。", "category": "彩妝"},
    {"name": "Integrate 櫻特芮 柔焦輕透粉底液", "features": "柔焦效果、輕薄自然。", "pain": "妝感太重、毛孔明顯。", "skin": "所有膚質。", "category": "彩妝"},
    {"name": "Addiction 癮彩眼影", "features": "多色可選、顯色度高。", "pain": "追求專業妝效、單色眼影收集。", "skin": "所有膚質。", "category": "彩妝"},
    {"name": "Benefit 貝玲妃 嘖嘖稱齊毛孔隱形露", "features": "填平毛孔、控油長效。", "pain": "橘子皮毛孔、出油脫妝。", "skin": "油性肌、混合肌。", "category": "彩妝"},

    # 更多頭髮護理 (Haircare)
    {"name": "Shiseido 資生堂 Fino 護髮膜 (紅罐)", "features": "高滲透美容液、柔順亮澤。", "pain": "分叉、斷裂、洗後乾澀。", "skin": "受損髮。", "category": "頭髮護理"},
    {"name": "Kao 花王 植萃頭皮護理洗髮精 (涼感)", "features": "薄荷舒爽、淨化毛孔。", "pain": "頭皮悶熱、異味、出油。", "skin": "油性頭皮。", "category": "頭髮護理"},
    {"name": "Amma Garden 艾瑪花園 綠色植萃洗髮精", "features": "天然配方、無矽靈。", "pain": "掉髮感、追求天然保養。", "skin": "所有髮質。", "category": "頭髮護理"},
    {"name": "L'Oreal 巴黎萊雅 絲漾博 護色洗髮精", "features": "延長髮色、增加亮度。", "pain": "染後掉色快、頭髮枯黃。", "skin": "染後髮質。", "category": "頭髮護理"},
    {"name": "Mise en Scene 魅尚萱 完美修護精油", "features": "韓系經典、七種植萃。", "pain": "靜電毛躁、難梳理。", "skin": "所有髮質。", "category": "頭髮護理"},
    {"name": "Schwarzkopf 施華蔻 專業抗熱噴霧", "features": "220度保護、預防熱傷害。", "pain": "常用電棒捲、吹風機傷髮。", "skin": "所有髮質。", "category": "頭髮護理"},
    {"name": "Lux 麗仕 膠原蛋白洗髮精", "features": "保濕成分、強韌髮絲。", "pain": "頭髮細軟、缺乏彈性。", "skin": "所有髮質。", "category": "頭髮護理"},
    {"name": "Dove 多芬 深層修護潤髮乳", "features": "修復受損、滋養纖維。", "pain": "髮尾乾枯、打結。", "skin": "受損髮。", "category": "頭髮護理"},
    {"name": "Aveda 蘊活菁華滋養液", "features": "草本頭皮保養、強化髮根。", "pain": "落髮明顯、髮縫寬、追求高級感。", "skin": "細軟稀疏髮。", "category": "頭髮護理"},
    {"name": "Nature's Gate 天然之扉 經典洗髮精", "features": "純淨草本、溫和清潔。", "pain": "追求環保、頭皮敏感。", "skin": "敏弱頭皮。", "category": "頭髮護理"},

    # 更多身體保養 (Body Care)
    {"name": "L'Occitane 歐舒丹 杏仁沐浴油", "features": "油狀質地、洗後柔嫩。", "pain": "洗後乾癢、不喜歡沐浴乳殘留感。", "skin": "乾性肌。", "category": "身體保養"},
    {"name": "Nivea 妮維雅 止汗爽身噴霧", "features": "48小時乾爽、不留痕跡。", "pain": "狐臭困擾、腋下出汗、衣物黃漬。", "skin": "所有膚質。", "category": "個人護理"},
    {"name": "Scholl 爽健 去硬皮機", "features": "滾輪設計、快速去角質。", "pain": "腳跟龜裂、厚繭、不敢穿涼鞋。", "skin": "足部肌膚。", "category": "個人護理"},
    {"name": "Burt's Bees 蜜蜂爺爺 護手霜", "features": "蜂蠟成分、深度滋潤。", "pain": "家事手、指縫裂、極度乾燥。", "skin": "極乾肌。", "category": "個人護理"},
    {"name": "Yuskin A 悠斯晶 A 乳霜", "features": "藥用修護、修復裂口。", "pain": "冬季乾裂、富貴手、腳跟裂。", "skin": "乾裂肌。", "category": "個人護理"},
    {"name": "Biore 蜜妮 涼感沐浴露", "features": "薄荷因子、清爽消暑。", "pain": "夏天洗完澡又流汗。", "skin": "所有膚質。", "category": "身體保養"},
    {"name": "Dove 多芬 去角質身體磨砂膏 (奇異果)", "features": "冰沙質地、去黑透亮。", "pain": "膝蓋手肘暗沈、皮膚粗糙。", "skin": "所有膚質。", "category": "身體保養"},
    {"name": "The Body Shop 茶樹身體潔膚露", "features": "茶樹精油、改善背痘。", "pain": "背部痘痘、毛囊炎。", "skin": "油性肌、痘痘肌。", "category": "身體保養"},
    {"name": "Johnson's 強生 嬰兒爽身粉 (舒眠)", "features": "細緻粉質、助眠香氛。", "pain": "汗疹、皮膚摩擦不適、助眠。", "skin": "所有人。", "category": "個人護理"},
    {"name": "Aveeno 艾惟諾 燕麥保濕乳 (藍瓶)", "features": "三重燕麥、舒緩乾癢。", "pain": "濕疹、敏弱肌搔癢。", "skin": "敏弱乾肌。", "category": "身體保養"},

    # 補充 150 項其他熱門項目 (快速生成)
    {"name": "Hada Labo 肌研 極潤健康化粧水", "features": "舒緩安定、調理膚況。", "pain": "肌膚不穩定、泛紅、粉刺。", "skin": "所有膚質。", "category": "化妝水"},
    {"name": "Curél 潤浸保濕深層乳霜 (新版)", "features": "神經醯胺、極簡溫和。", "pain": "換季過敏、醫美後修復。", "skin": "敏感肌。", "category": "乳霜"},
    {"name": "Melano CC 維他命C美白精華液 (加強版)", "features": "雙重維他命、滲透力強。", "pain": "頑固痘疤、斑點、膚色不均。", "skin": "所有膚質。", "category": "精華"},
    {"name": "Senka 專科 完美防曬水凝膠", "features": "SPF50+、肥皂可卸。", "pain": "懶人防曬、不喜歡卸身體防曬。", "skin": "所有膚質。", "category": "防曬"},
    {"name": "Biore 蜜妮 淨嫩沐浴乳 (櫻花香)", "features": "洗後水潤、持久香氛。", "pain": "追求洗後感、香味持久度。", "skin": "所有膚質。", "category": "身體保養"},
    {"name": "Mentholatum 曼秀雷敦 護唇膏 (薄荷)", "features": "經典綠管、沁涼修護。", "pain": "嘴唇乾裂、提神。", "skin": "所有人。", "category": "唇部"},
    {"name": "Vaseline 凡士林 專業低敏修護霜", "features": "深層修復、無添加。", "pain": "極度乾癢、濕疹。", "skin": "極乾敏肌。", "category": "乳霜"},
    {"name": "Dr.Wu 達爾膚 玻尿酸保濕精華液", "features": "五代玻尿酸、專業醫美。", "pain": "高效補水、術後保養。", "skin": "所有膚質。", "category": "精華"},
    {"name": "Bioderma 貝膚黛瑪 舒敏高效潔膚液 (大瓶裝)", "features": "溫和卸妝、無需沖洗。", "pain": "懶得洗臉、敏感肌卸妝。", "skin": "敏感肌。", "category": "卸妝"},
    {"name": "Senka 專科 完美保濕洗顏霜", "features": "蠶絲蛋白、保濕泡沫。", "pain": "洗後乾澀、泡沫不夠綿密。", "skin": "所有膚質。", "category": "洗面乳"},
    # ... 接下來我會補齊到 200 個 ...
    # 由於空間限制，我會在這裡直接列出更多項目
    {"name": "CeraVe 適樂膚 長效清爽保濕乳", "features": "清爽質地、神經醯胺。", "pain": "乳液太厚、敏感肌保養。", "skin": "敏感肌、所有膚質。", "category": "乳霜"},
    {"name": "La Roche-Posay 理膚寶水 多容安舒緩保濕乳", "features": "安心霜、舒緩泛紅。", "pain": "極度敏感、發熱泛紅。", "skin": "敏弱肌。", "category": "乳霜"},
    {"name": "Hada Labo 肌研 白潤美白化妝水", "features": "高純度傳明酸、水潤提亮。", "pain": "曬後修復、想變白。", "skin": "所有膚質。", "category": "化妝水"},
    {"name": "Minon 氨基酸保濕面膜", "features": "濃潤美容液、低刺激。", "pain": "乾荒肌急救、敏感期面膜。", "skin": "敏感肌、乾性肌。", "category": "面膜"},
    {"name": "My Beauty Diary 我的美麗日記 黑珍珠煥白面膜", "features": "珍珠精華、透亮光澤。", "pain": "臉色灰暗、蠟黃。", "skin": "所有膚質。", "category": "面膜"},
    {"name": "Dr.Wu 杏仁酸亮白煥膚精華 18%", "features": "18%黃金比例、煥膚去角質。", "pain": "老廢角質、閉口粉刺、毛孔粗大。", "skin": "油性肌、混合肌。", "category": "精華"},
    {"name": "Paula's Choice 寶拉珍選 淨無痘2%水楊酸美體噴霧", "features": "360度噴頭、倒著噴背。", "pain": "背痘、身體粗糙、角化問題。", "skin": "所有膚質。", "category": "身體保養"},
    {"name": "Neutrogena 露得清 水活保濕凝露", "features": "玻尿酸、漸進釋放。", "pain": "鎖水力不足、保養品不吸收。", "skin": "所有膚質。", "category": "乳霜"},
    {"name": "Biore 蜜妮 含水防曬保濕水凝乳", "features": "水感質地、SPF50+。", "pain": "怕油膩、防曬長痘。", "skin": "所有膚質。", "category": "防曬"},
    {"name": "DHC 睫毛修護液", "features": "植物萃取、強韌睫毛。", "pain": "睫毛易斷、稀疏、想接睫毛後保養。", "skin": "所有人。", "category": "彩妝"},
    {"name": "Canmake 絲滑透亮腮紅", "features": "自然紅潤、透明感。", "pain": "氣色不佳、妝感厚重。", "skin": "所有膚質。", "category": "彩妝"},
    {"name": "Opera 渲漾水色唇膏 (限定色)", "features": "水潤顯色、花嫁唇膏。", "pain": "乾唇、追求日系清透妝感。", "skin": "所有膚質。", "category": "唇部"},
    {"name": "Kate 凱婷 3D造型眉彩膏", "features": "修飾眉色、立體感。", "pain": "眉色太深、眉毛稀疏。", "skin": "所有人群。", "category": "彩妝"},
    {"name": "Maybelline 媚比琳 飛天翹防水睫毛膏", "features": "不垂長翹、扇形刷頭。", "pain": "垂頭睫毛、不夠濃密。", "skin": "所有人群。", "category": "彩妝"},
    {"name": "Za 美白粉底液", "features": "美白保養、輕透底妝。", "pain": "邊化妝邊美白、膚色暗沈。", "skin": "所有膚質。", "category": "彩妝"},
    {"name": "heme 喜蜜 純色眼影", "features": "單色自組、粉質服貼。", "pain": "眼影盤用不完、只想買特定顏色。", "skin": "所有膚質。", "category": "彩妝"},
    {"name": "1028 放色線持久眼線液", "features": "0.01mm極細、抗暈染。", "pain": "眼線畫不好、眼皮出油。", "skin": "所有膚質。", "category": "彩妝"},
    {"name": "Kiss Me 花漾美姬 濃黑睫毛膏", "features": "防水極黑、經典神品。", "pain": "睫毛稀疏、追求極致濃密。", "skin": "所有人群。", "category": "彩妝"},
    {"name": "Sofina 漾緁 控油瓷效妝前隔離乳 (升級)", "features": "更長效控油、粉嫩提亮。", "pain": "中東油田、妝不持久。", "skin": "油性肌。", "category": "彩妝"},
    {"name": "Integrate 櫻特芮 迷人光采粉底膏", "features": "高遮瑕、保濕滋潤。", "pain": "瑕疵多、肌膚乾燥不貼妝。", "skin": "乾性肌、混合肌。", "category": "彩妝"},
    {"name": "Shiseido 資生堂 嘉美艷容露", "features": "經典配方、鎮定消炎。", "pain": "痘痘紅腫、日曬後發紅。", "skin": "油痘肌。", "category": "化妝水"},
    {"name": "Kose 高絲 絲芙蒂 瞬淨卸妝油", "features": "快速乳化、手濕可用。", "pain": "洗澡順便卸妝、懶人必備。", "skin": "所有膚質。", "category": "卸妝"},
    {"name": "Bifesta 碧菲絲特 毛孔即淨卸妝棉", "features": "含化妝水成分、溫和去角質。", "pain": "旅遊懶得帶瓶瓶罐罐。", "skin": "所有膚質。", "category": "卸妝"},
    {"name": "Senka 專科 超微米洗顏乳 (藍瓶)", "features": "濃密蠶絲泡、洗後不緊繃。", "pain": "清潔力不夠、不喜歡泡泡稀疏。", "skin": "所有膚質。", "category": "洗面乳"},
    {"name": "Senka 專科 超微米深層潔顏泥", "features": "海泥配方、深層吸油。", "pain": "黑頭粉刺、出油嚴重。", "skin": "油性肌。", "category": "洗面乳"},
    {"name": "Curél 潤浸保濕洗顏慕斯", "features": "慕斯質地、保護神經醯胺。", "pain": "洗後緊繃乾癢、敏感肌洗臉。", "skin": "敏感肌。", "category": "洗面乳"},
    {"name": "Dr.Wu 達爾膚 杏仁酸煥膚潔顏慕斯", "features": "酸類清潔、代謝粉刺。", "pain": "粗糙肌、粉刺多。", "skin": "混合肌、油性肌。", "category": "洗面乳"},
    {"name": "Avène 雅漾 舒護活泉水 (大瓶)", "features": "純淨活泉、舒緩噴霧。", "pain": "肌膚燥熱、過敏不適、隨時補水。", "skin": "所有膚質。", "category": "化妝水"},
    {"name": "Bioderma 貝膚黛瑪 舒敏高效潔膚液", "features": "敏弱肌專用、卸妝神水。", "pain": "卸妝刺痛、眼唇卸不乾淨。", "skin": "敏感肌。", "category": "卸妝"},
    {"name": "Eucerin 伊思妮 舒安修護霜", "features": "抗泛紅、極速舒緩。", "pain": "肌膚發燙、敏感性紅斑。", "skin": "極敏肌。", "category": "乳霜"},
    {"name": "Bio-Oil 百洛護膚油 (小瓶)", "features": "修復疤痕、改善紋路。", "pain": "身體小瑕疵、局部乾燥。", "skin": "所有膚質。", "category": "身體保養"},
    {"name": "Sabon 經典沐浴油", "features": "精油保養、層次香氛。", "pain": "追求沐浴質感、儀式感。", "skin": "所有膚質。", "category": "身體保養"},
    {"name": "L'Occitane 歐舒丹 乳油木身體乳", "features": "乳油木果、長效滋潤。", "pain": "冬季乾癢、皮膚脫屑。", "skin": "乾性肌。", "category": "身體保養"},
    {"name": "Vaseline 凡士林 專業低敏修護乳液 (大瓶)", "features": "醫生推薦、高效鎖水。", "pain": "全家人乾癢困擾、濕疹肌。", "skin": "所有人。", "category": "身體保養"},
    {"name": "Nivea 妮維雅 潤膚霜 (藍罐)", "features": "德製經典、全身可用。", "pain": "極度乾裂、厚敷修復。", "skin": "乾性肌。", "category": "身體保養"},
    {"name": "Scholl 爽健 護足霜", "features": "深度保濕、修復龜裂。", "pain": "腳跟粗糙、厚繭。", "skin": "足部肌。", "category": "個人護理"},
    {"name": "Johnson's 強生 嬰兒沐浴乳 (溫和)", "features": "不掉淚配方、pH平衡。", "pain": "小孩洗澡、全家共用。", "skin": "嬰幼兒、所有人。", "category": "個人護理"},
    {"name": "Cetaphil 舒特膚 溫和潔膚乳 (大瓶)", "features": "醫學品牌、免沖水也可。", "pain": "術後不能碰水、極度敏感。", "skin": "極敏肌。", "category": "洗面乳"},
    {"name": "Cetaphil 舒特膚 潤膚乳液", "features": "不含香料、全家適用。", "pain": "大面積乾癢、追求簡單保養。", "skin": "所有人。", "category": "身體保養"},
    {"name": "La Roche-Posay 理膚寶水 全護清爽防曬液", "features": "抗UVA、防曬老。", "pain": "怕曬黑、怕長斑、追求高防護。", "skin": "所有膚質。", "category": "防曬"},
    {"name": "Skin Aqua 曼秀雷敦 水潤肌柔光透亮防曬飾底凝露", "features": "薰衣草紫、校正膚色。", "pain": "蠟黃肌、想要偽素顏妝感。", "skin": "蠟黃肌、所有膚質。", "category": "防曬"},
    {"name": "Biore 蜜妮 A極效防曬乳 (戶外專用)", "features": "極效抗水抗汗、持久防禦。", "pain": "衝浪、海邊活動、極端環境。", "skin": "所有膚質。", "category": "防曬"},
    {"name": "Anessa 安耐曬 金鑽高效防曬露 (升級)", "features": "熱能傳導技術、越熱越強。", "pain": "烈日下活動、怕曬傷。", "skin": "所有膚質。", "category": "防曬"},
    {"name": "Suncut 曬可艾 防曬噴霧 (大容量)", "features": "清爽不黏、快速大面積。", "pain": "身體補擦太麻煩、噴霧更均勻。", "skin": "所有膚質。", "category": "防曬"},
    {"name": "Mentholatum 曼秀雷敦 抗痘隔離霜", "features": "潤色抗痘、SPF50+。", "pain": "長痘痘想化妝、防曬抗痘兩合一。", "skin": "油痘肌。", "category": "防曬"},
    {"name": "DHC 橄欖卸妝油", "features": "經典明星商品、深層卸除。", "pain": "濃妝難卸、追求純植物油。", "skin": "所有膚質。", "category": "卸妝"},
    {"name": "Softymo 絲芙蒂 卸妝液 (眼唇專用)", "features": "溫和不刺眼、高效率。", "pain": "眼線液睫毛膏卸不乾淨。", "skin": "所有人。", "category": "卸妝"},
    {"name": "Melano CC 維他命C酵素深層洗面乳", "features": "酵素洗淨、亮白去黑。", "pain": "毛孔暗沈、洗後提亮。", "skin": "所有膚質。", "category": "洗面乳"},
    {"name": "Labo Labo 毛孔緊膚精華水", "features": "縮小毛孔、控制油分。", "pain": "出油旺盛、毛孔明顯。", "skin": "油性肌。", "category": "化妝水"},
    {"name": "广源良 蘆薈洗面乳", "features": "台灣經典、舒緩清爽。", "pain": "洗後緊繃感、追求在地品牌。", "skin": "所有膚質。", "category": "洗面乳"},
    {"name": "广源良 噴霧化妝水 (絲瓜水)", "features": "100%絲瓜水、純天然。", "pain": "肌膚燥熱、日常補水、便宜大碗。", "skin": "所有膚質。", "category": "化妝水"},
    {"name": "雪芙蘭 滋養霜 (綿羊油)", "features": "深度滋潤、老牌口碑。", "pain": "冬季脫皮、關節粗糙。", "skin": "乾性肌。", "category": "身體保養"},
    {"name": "雪芙蘭 美白身體乳", "features": "大容量、CP值高。", "pain": "身體曬黑、想大量塗抹美白。", "skin": "所有人。", "category": "身體保養"},
    {"name": "Vaseline 凡士林 專業修護潤膚膏 (原味)", "features": "萬用膏、鎖水第一。", "pain": "局部極乾、嘴唇乾裂、輕微燙傷。", "skin": "所有人。", "category": "個人護理"},
    {"name": "Senka 專科 完美水感防曬乳", "features": "極輕透、不泛白。", "pain": "防曬像戴面具、厚重感。", "skin": "所有膚質。", "category": "防曬"},
    {"name": "Nivea 妮維雅 男士控油洗面乳", "features": "火山泥配方、深層潔淨。", "pain": "男士臉部油膩、毛孔粗大。", "skin": "男士、油性肌。", "category": "男性保養"},
    {"name": "Nivea 妮維雅 男士保濕乳液", "features": "清爽補水、無黏膩感。", "pain": "男士不喜歡擦保養品的黏膩感。", "skin": "男士。", "category": "男性保養"},
    {"name": "Mentholatum 曼秀雷敦 藥用抗痘洗面乳 (加強)", "features": "三效合一、預防痘痘。", "pain": "反覆長痘、油水失衡。", "skin": "油痘肌。", "category": "洗面乳"},
    {"name": "Hada Labo 肌研 極潤保濕洗顏慕斯 (補充包)", "features": "環保省錢、細緻泡泡。", "pain": "泡沫用量大、想省錢。", "skin": "所有膚質。", "category": "洗面乳"},
    {"name": "Minon 氨基酸保濕乳液 (補充包)", "features": "敏感肌必備、保濕不膩。", "pain": "回購首選、環保經濟。", "skin": "敏感肌。", "category": "乳霜"},
    {"name": "Curél 潤浸保濕沐浴露 (補充包)", "features": "保護屏障、洗後舒緩。", "pain": "全家人洗澡用量大、省錢環保。", "skin": "敏感肌、乾性肌。", "category": "身體保養"},
    {"name": "Dove 多芬 輕透保濕沐浴乳", "features": "質地清爽、夏日專用。", "pain": "冬天沐浴乳太厚重。", "skin": "所有膚質。", "category": "身體保養"},
    {"name": "Johnson's 強生 嬰兒洗髮精 (黃瓶)", "features": "無淚配方、經典香氣。", "pain": "小孩不愛洗頭、追求簡單。", "skin": "嬰幼兒。", "category": "頭髮護理"},
    {"name": "Clear 淨 男士去屑洗髮乳 (控油型)", "features": "超強控油、酷爽感。", "pain": "男士頭皮屑、夏天頭皮臭。", "skin": "男士、油性頭皮。", "category": "頭髮護理"},
    {"name": "Head & Shoulders 海倫仙度絲 男士專用去屑洗髮乳", "features": "針對男士頭皮、深層淨化。", "pain": "頑固頭皮屑、癢感。", "skin": "男士。", "category": "頭髮護理"},
    {"name": "Batiste 秀髮乾洗噴霧 (經典原味)", "features": "隨身瓶、立即蓬鬆。", "pain": "旅遊、外宿、瀏海急救。", "skin": "所有髮質。", "category": "頭髮護理"},
    {"name": "Tsubaki 思波綺 瞬亮修護護髮乳", "features": "沙龍級效果、居家保養。", "pain": "沒時間去髮廊、頭髮毛躁。", "skin": "所有髮質。", "category": "頭髮護理"},
    {"name": "Lux 麗仕 柔亮洗髮精", "features": "深層滋潤、閃耀光澤。", "pain": "頭髮暗沈、缺乏生氣。", "skin": "所有髮質。", "category": "頭髮護理"},
    {"name": "Pantene 潘婷 3分鐘奇蹟護髮精華素", "features": "快速修復、高濃度維他命。", "pain": "沒時間護髮、頭髮急救。", "skin": "受損髮。", "category": "頭髮護理"},
    {"name": "Essential 逸萱秀 瞬效護髮膜", "features": "30秒沖洗、快速柔順。", "pain": "洗澡趕時間、頭髮易打結。", "skin": "所有髮質。", "category": "頭髮護理"},
    {"name": "Mod's Hair 蓬鬆慕斯", "features": "持久定型、空氣感。", "pain": "髮根扁塌、細軟髮質造型難。", "skin": "細軟髮。", "category": "頭髮護理"},
    {"name": "Gatsby 定型噴霧 (加強型)", "features": "強效定型、抗濕氣。", "pain": "男士造型走樣、風大雨大妝不亂。", "skin": "男士。", "category": "頭髮護理"},
    {"name": "Batiste 秀髮乾洗噴霧 (淡雅花香)", "features": "除臭留香、蓬鬆效果。", "pain": "火鍋燒肉後頭髮臭。", "skin": "所有人。", "category": "頭髮護理"},
    {"name": "Kao 花王 泡泡染髮劑 (多色)", "features": "在家輕鬆染、均勻顯色。", "pain": "去沙龍太貴、白髮困擾、想換髮色。", "skin": "所有人。", "category": "頭髮護理"},
    {"name": "Schwarzkopf 施華蔻 專業染髮霜", "features": "持久顯色、附贈護髮。", "pain": "白髮遮蓋、在家染髮效果差。", "skin": "所有人。", "category": "頭髮護理"},
    {"name": "Saborino 晚安面膜 (莓果型)", "features": "高保濕、夜間修復。", "pain": "熬夜臉色差、懶人夜間保養。", "skin": "所有膚質。", "category": "面膜"},
    {"name": "Utena 佑天蘭 黃金果凍面膜 (膠原蛋白)", "features": "豐富膠原、提升彈性。", "pain": "肌膚鬆弛、乾癟感。", "skin": "熟齡肌、乾性肌。", "category": "面膜"},
    {"name": "Kose 高絲 透明質酸面膜 (大包裝)", "features": "高CP值、天天敷不心疼。", "pain": "預算有限、需要大量補水。", "skin": "所有膚質。", "category": "面膜"},
    {"name": "LuLuLun 粉色保濕面膜 (日常用)", "features": "基礎保濕、平衡肌膚。", "pain": "肌膚基礎不穩定、缺水。", "skin": "所有膚質。", "category": "面膜"},
    {"name": "Dr.Jart+ 補水膠囊面膜 (二入)", "features": "專業修護、深度補水。", "pain": "肌膚大脫皮、醫美術後。", "skin": "極乾肌、受損肌。", "category": "面膜"},
    {"name": "Abib 弱酸性口香糖面膜 (魚腥草)", "features": "極致服貼、鎮定泛紅。", "pain": "面膜不服貼、肌膚發熱發癢。", "skin": "敏感肌。", "category": "面膜"},
    {"name": "Mediheal 提拉保濕面膜", "features": "緊緻輪廓、高濃度精華。", "pain": "水腫、追求小臉感、深度滋養。", "skin": "熟齡肌。", "category": "面膜"},
    {"name": "Paparecipe 春雨黑蜂蜜面膜", "features": "深層淨化、溫和美白。", "pain": "暗沈、想排毒淨化肌膚。", "skin": "所有膚質。", "category": "面膜"},
    {"name": "Papa Recipe 綠泥面膜", "features": "控油去角質、植物成分。", "pain": "油性肌清潔、粉刺問題。", "skin": "油性肌。", "category": "面膜"},
    {"name": "Innisfree 濟州島綠茶面膜", "features": "抗氧化、清爽補水。", "pain": "夏天曬後、肌膚疲憊。", "skin": "所有膚質。", "category": "面膜"},
    {"name": "Nature Republic 蘆薈凝膠面膜", "features": "曬後鎮定、便宜大碗。", "pain": "全身曬傷、大面積舒緩。", "skin": "所有人。", "category": "面膜"},
    {"name": "Hada Labo 肌研 極潤保濕精華液 (升級)", "features": "分子更小、更好吸收。", "pain": "精華液太黏、保濕不夠深。", "skin": "所有膚質。", "category": "精華"},
    {"name": "Dr.Wu 達爾膚 VC美白精華", "features": "三效美白、抑制黑色素。", "pain": "曬斑、痘印、膚色暗沈。", "skin": "所有膚質。", "category": "精華"},
    {"name": "Neogence 霓淨思 積雪草舒緩修護精華", "features": "95%高純度積雪草、修復力強。", "pain": "泛紅、乾癢、不穩定。", "skin": "敏感肌、受損肌。", "category": "精華"},
    {"name": "The Ordinary 玻尿酸2% + B5精華", "features": "超高CP值、保濕之王。", "pain": "預算有限、單純保濕需求。", "skin": "所有膚質。", "category": "精華"},
    {"name": "Paula's Choice 寶拉珍選 1%視黃醇精華乳", "features": "抗老神品、縮小毛孔。", "pain": "皺紋、老化、毛孔粗大。", "skin": "熟齡肌、油性肌。", "category": "精華"},
    {"name": "CeraVe 適樂膚 視黃醇修護精華", "features": "溫和A醇、神經醯胺保護。", "pain": "想嘗試A醇又怕過敏、痘疤修復。", "skin": "敏感肌、初次使用者。", "category": "精華"},
    {"name": "La Roche-Posay 理膚寶水 C10肌光活膚精華", "features": "10%維他命C、溫和亮白。", "pain": "敏感肌想美白、皮膚粗糙暗沈。", "skin": "敏感肌、所有膚質。", "category": "精華"},
    {"name": "Biotherm 碧兒泉 奇蹟特嫩精華", "features": "活源精華、改善顆粒感。", "pain": "皮膚摸起來粗粗的、代謝不佳。", "skin": "所有膚質。", "category": "精華"},
    {"name": "Kiehl's 契爾氏 激光極淨白淡斑精華 (大瓶)", "features": "明星商品、美白淡斑。", "pain": "頑固黑斑、痘疤。", "skin": "所有膚質。", "category": "精華"},
    {"name": "Shiseido 資生堂 小紅瓶 (紅妍超導循環肌活露)", "features": "增強免疫力、修復穩定。", "pain": "肌膚容易出狀況、老化、暗沈。", "skin": "所有膚質。", "category": "精華"},
    {"name": "Estee Lauder 雅詩蘭黛 小棕瓶 (特潤超導修護露)", "features": "夜間修復、經典之作。", "pain": "皺紋、失去光澤、急救修護。", "skin": "所有膚質。", "category": "精華"},
    {"name": "Lancome 蘭蔻 小黑瓶 (超未來肌因賦活露)", "features": "微生態平衡、細緻肌膚。", "pain": "毛孔、粗糙、肌膚不穩定。", "skin": "所有膚質。", "category": "精華"},
    {"name": "SK-II 青春露 (體驗瓶)", "features": "Pitera成分、神仙水。", "pain": "想體驗晶瑩剔透、改善膚質。", "skin": "所有膚質。", "category": "化妝水"},
    {"name": "Clinique 倩碧 潔膚水2號", "features": "溫和去角質、清理皮層。", "pain": "擦出髒污、保養品吸收差。", "skin": "混合肌、乾性肌。", "category": "化妝水"},
    {"name": "Origins 品木宣言 靈芝水 (200ml)", "features": "草本修復、舒緩泛紅。", "pain": "換季不穩、敏感泛紅。", "skin": "敏感肌、所有膚質。", "category": "化妝水"},
    {"name": "Kose 高絲 雪肌精 (經典瓶)", "features": "漢方美白、清爽控油。", "pain": "想變白、曬後鎮定、油光。", "skin": "混合肌、油性肌。", "category": "化妝水"},
    {"name": "Hada Labo 肌研 極潤保濕乳液 (大瓶)", "features": "四重玻尿酸、無香料。", "pain": "基礎保養、溫和不刺激。", "skin": "所有人。", "category": "乳霜"},
    {"name": "Minon 氨基酸保濕乳霜", "features": "密封補水、強效滋潤。", "pain": "極度乾旱肌、脫屑。", "skin": "乾性肌、敏感肌。", "category": "乳霜"},
    {"name": "Curél 潤浸保濕深層乳霜", "features": "獲獎無數、敏感肌救星。", "pain": "什麼都不能擦、過敏泛紅。", "skin": "極敏肌。", "category": "乳霜"},
    {"name": "Vaseline 凡士林 專業低敏修護霜 (特大)", "features": "超高性價比、全身可用。", "pain": "大面積皮膚炎傾向、乾癢。", "skin": "所有人。", "category": "身體保養"},
    {"name": "Nivea 妮維雅 止汗爽身乳膏", "features": "持久乾爽、攜帶方便。", "pain": "男士狐臭、運動後異味。", "skin": "男士。", "category": "個人護理"},
    {"name": "Mentholatum 曼秀雷敦 軟膏 (經典紅蓋)", "features": "小護士、居家必備。", "pain": "蚊蟲叮咬、擦傷、局部不適。", "skin": "所有人。", "category": "個人護理"},
    {"name": "Darlie 好來 雙重薄荷牙膏", "features": "超涼口感、口氣清新。", "pain": "口臭、早起口腔不適。", "skin": "所有人。", "category": "個人護理"},
    {"name": "Oral-B 歐樂B 電動牙刷 (入門型)", "features": "旋轉清潔、比手動更乾淨。", "pain": "刷牙不乾淨、牙周問題。", "skin": "所有人。", "category": "個人護理"},
    {"name": "Listerine 李施德霖 薄荷漱口水", "features": "殺菌抑菌、清爽薄荷。", "pain": "口腔清潔死角、口臭。", "skin": "所有人。", "category": "個人護理"},
    {"name": "Ora2 me 淨白無瑕漱口水", "features": "不辛辣、溫和去漬。", "pain": "怕辣、想維持牙齒亮白。", "skin": "所有人。", "category": "個人護理"},
    {"name": "DHC 藍莓精華 (60日份)", "features": "護眼成分、高花青素。", "pain": "長時間看螢幕、眼睛疲勞。", "skin": "所有人。", "category": "保健食品"},
    {"name": "Fancl 芳珂 健體B群 (30日份)", "features": "長效型B群、活力充沛。", "pain": "易累、作息不穩。", "skin": "所有人。", "category": "保健食品"},
    {"name": "Chocola BB Royal T 皇家滋養錠", "features": "蜂王乳添加、女性活力。", "pain": "氣色差、疲倦、想要亮麗感。", "skin": "女性。", "category": "保健食品"},
    {"name": "Haba 鯊烯美肌油 (15ml)", "features": "一滴萬用、純度99.9%。", "pain": "保養品不夠潤、鎖水力差。", "skin": "所有膚質。", "category": "精華"},
    {"name": "Biore 蜜妮 頂級深層卸妝棉", "features": "含大容量美容液、不緊繃。", "pain": "卸妝後皮膚乾澀。", "skin": "所有膚質。", "category": "卸妝"},
    {"name": "Maybelline 媚比琳 眼唇卸妝液 (大瓶)", "features": "經典油水分離、不熏眼。", "pain": "防水妝難卸、追求CP值。", "skin": "所有人。", "category": "卸妝"},
    {"name": "Biore 蜜妮 男士沁涼去油洗面乳 (加強)", "features": "極效去油、瞬間降溫。", "pain": "男士夏天油膩、汗味。", "skin": "男士。", "category": "男性保養"},
    {"name": "L'Oreal 巴黎萊雅 男士勁能深層洗面露", "features": "炭黑成分、吸附髒污。", "pain": "黑頭粉刺、環境污染污染。", "skin": "男士。", "category": "男性保養"},
    {"name": "UNO 完效男人保濕乳 (清爽型)", "features": "全效合一、不黏膩。", "pain": "懶人保養、追求清爽。", "skin": "男士。", "category": "男性保養"},
    {"name": "Gatsby 塑型髮蠟 (消光型)", "features": "霧面妝感、超強定型。", "pain": "不喜歡頭髮發亮、想要自然定型。", "skin": "男士。", "category": "頭髮護理"},
    {"name": "Mentholatum 曼秀雷敦 男士潤唇膏", "features": "無色無味、極簡包裝。", "pain": "男士嘴唇乾裂、怕亮亮的。", "skin": "男士。", "category": "唇部"},
    {"name": "Schwarzkopf 施華蔻 專業抗老洗髮精", "features": "強化髮絲結構、防斷裂。", "pain": "髮絲脆弱、老化無力。", "skin": "所有人。", "category": "頭髮護理"},
    {"name": "Aromase 艾瑪絲 去屑止癢洗髮精", "features": "草本抑菌、舒緩頭皮。", "pain": "反覆頭皮屑、頭皮紅癢。", "skin": "問題頭皮。", "category": "頭髮護理"},
    {"name": "Batiste 秀髮乾洗噴霧 (熱帶風情)", "features": "椰子香氣、立即清爽。", "pain": "夏天異味、頭油。", "skin": "所有人。", "category": "頭髮護理"},
    {"name": "Mod's Hair 熱感造型水", "features": "熱保護、定型持久。", "pain": "造型容易塌、怕熱傷害。", "skin": "所有人。", "category": "頭髮護理"},
    {"name": "Batiste 秀髮乾洗噴霧 (隨身包)", "features": "迷你包裝、不佔空間。", "pain": "小包包必備、急救用。", "skin": "所有人。", "category": "頭髮護理"},
    {"name": "LuLuLun 綠色平衡面膜 (日常)", "features": "調節膚況、改善粗糙。", "pain": "肌膚摸起來不平整。", "skin": "所有膚質。", "category": "面膜"},
    {"name": "My Beauty Diary 我的美麗日記 官燕窩面膜", "features": "極致滋養、彈潤亮澤。", "pain": "臉部乾癟、失去彈性。", "skin": "乾性肌。", "category": "面膜"},
    {"name": "Dr.Jart+ 活力保濕精華水", "features": "補水第一步、質地清爽。", "pain": "洗完臉緊繃、後續保養不吸收。", "skin": "所有膚質。", "category": "化妝水"},
    {"name": "Abib 魚腥草舒緩噴霧", "features": "隨時鎮定、霧化細膩。", "pain": "辦公室乾燥、泛紅不適。", "skin": "敏感肌、所有膚質。", "category": "化妝水"},
    {"name": "Torriden 潛水艇玻尿酸精華 (大容量)", "features": "韓系補水王、分子極小。", "pain": "深度缺水、想要水光感。", "skin": "所有膚質。", "category": "精華"},
    {"name": "Medicube 零毛孔修護精華", "features": "緊緻毛孔、平衡油脂。", "pain": "毛孔大、出油旺盛。", "skin": "油性肌。", "category": "精華"},
    {"name": "Beauty of Joseon 朝鮮美女 大米亮白防曬霜", "features": "穀物成分、不泛白不油膩。", "pain": "不喜歡防曬味、追求韓系亮白。", "skin": "所有膚質。", "category": "防曬"},
    {"name": "Innisfree 綠茶平衡乳液", "features": "清爽控油、水油平衡。", "pain": "T字油兩頰乾、保養品太油。", "skin": "混合肌。", "category": "乳霜"},
    {"name": "Cosrx 蝸牛修護霜", "features": "92%蝸牛萃取、強效修護。", "pain": "肌膚受損、痘疤、乾燥。", "skin": "所有膚質。", "category": "乳霜"},
    {"name": "Cosrx 蜂膠滋養水", "features": "72%蜂膠、增加光澤。", "pain": "肌膚暗沈無光、免疫力差。", "skin": "所有膚質。", "category": "化妝水"},
    {"name": "Round Lab 白樺樹保濕化妝水", "features": "天然樹汁、極速補水。", "pain": "極度缺水、追求天然保養。", "skin": "所有膚質。", "category": "化妝水"},
    {"name": "The Body Shop 茶樹精油", "features": "經典抗痘、天然殺菌。", "pain": "突發大痘痘、粉刺發炎。", "skin": "痘痘肌。", "category": "精華"},
    {"name": "The Body Shop 維他命E晚霜", "features": "強效抗氧、滋潤保護。", "pain": "夜間修復、預防初老。", "skin": "所有膚質。", "category": "乳霜"},
    {"name": "Elizabeth Arden 伊麗莎白雅頓 黃金導航膠囊", "features": "神經醯胺、抗老經典。", "pain": "深度皺紋、老化脫屑。", "skin": "熟齡肌。", "category": "精華"},
    {"name": "Clinique 倩碧 水磁場72H保濕凝膠", "features": "超強鎖水、不含油分。", "pain": "缺水引起的出油、妝前保濕。", "skin": "所有膚質。", "category": "乳霜"},
    {"name": "Biotherm 碧兒泉 活泉保濕噴霧", "features": "礦物補水、提神醒膚。", "pain": "冷氣房乾燥、疲憊肌。", "skin": "所有人。", "category": "化妝水"},
    {"name": "Estee Lauder 雅詩蘭黛 原生露", "features": "微精華、強韌肌底。", "pain": "肌膚脆弱、吸收力差。", "skin": "所有膚質。", "category": "化妝水"},
    {"name": "Lancome 蘭蔻 極光水", "features": "酵素科技、拋光肌膚。", "pain": "顆粒感、毛孔粗大、暗沈。", "skin": "混合肌、油性肌。", "category": "化妝水"}
]

added_count = 0
for item in new_items_200:
    if item["name"] not in existing_names:
        data.append(item)
        existing_names.add(item["name"])
        added_count += 1

DB_PATH.write_text(json.dumps(data, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
print(f"Added {added_count} more items. Total: {len(data)}")
